'use client';

import { useEffect, useState } from 'react';
import { fetchAdmin } from '@/lib/adminFetch';

type Comanda = { id: string; status: string; mesa_referencia: string; valor_informado?: number | null; saipos_sale_id?: string | null; criado_por_nome?: string | null; criado_em: string; revisada_por_nome?: string | null; revisada_em?: string | null; motivo_revisao?: string | null; expira_em: string };

export default function ComandasPage() {
  const [comandas, setComandas] = useState<Comanda[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [imageUrl, setImageUrl] = useState<string | null>(null); const [working, setWorking] = useState<string | null>(null);
  async function carregar() { setLoading(true); try { const response = await fetchAdmin('/api/roleta-v2/comandas', { cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Não foi possível carregar.'); setComandas(data.comandas || []); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível carregar.'); } finally { setLoading(false); } }
  useEffect(() => { carregar(); }, []);
  async function abrirFoto(id: string) { setError(''); try { const response = await fetchAdmin(`/api/roleta-v2/comandas/${id}/imagem`, { cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Não foi possível abrir a foto.'); setImageUrl(data.url); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível abrir a foto.'); } }
  async function revisar(id: string, acao: 'em_analise' | 'rejeitada') { const motivo = window.prompt(acao === 'rejeitada' ? 'Motivo da rejeição:' : 'Registro da conferência:'); if (!motivo || motivo.trim().length < 3) return; setWorking(id); try { const response = await fetchAdmin(`/api/roleta-v2/comandas/${id}/revisar`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ acao, motivo }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Não foi possível registrar a revisão.'); await carregar(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível registrar a revisão.'); } finally { setWorking(null); } }
  return <div className="admin-operators"><section className="admin-notice"><strong>Conferência separada</strong><span>Garçom apenas envia a foto. Caixa não libera Roleta. Gestão e administração podem ver a foto privada e registrar a análise; esta versão não gera QR automaticamente.</span></section>{error && <div className="admin-notice error"><span>{error}</span></div>}{imageUrl && <section className="admin-operator-invite"><div className="admin-section-title"><div><span>Foto privada</span><h2>Conferir comanda</h2></div><button onClick={() => setImageUrl(null)}>Fechar</button></div><img src={imageUrl} alt="Foto privada da comanda" className="max-h-[70vh] rounded-lg border border-stone-300" /></section>}<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Quando</th><th>Mesa</th><th>Enviado por</th><th>Status</th><th>Conferência</th></tr></thead><tbody>{comandas.map((comanda) => <tr key={comanda.id}><td>{new Date(comanda.criado_em).toLocaleString('pt-BR')}</td><td><strong>{comanda.mesa_referencia}</strong></td><td>{comanda.criado_por_nome || '—'}</td><td>{comanda.status}</td><td><button onClick={() => abrirFoto(comanda.id)}>Ver foto</button>{['enviada', 'em_analise'].includes(comanda.status) && <><button onClick={() => revisar(comanda.id, 'em_analise')} disabled={working === comanda.id}>{working === comanda.id ? 'Salvando…' : 'Em análise'}</button><button className="admin-danger-button" onClick={() => revisar(comanda.id, 'rejeitada')} disabled={working === comanda.id}>Rejeitar</button></>} {comanda.motivo_revisao && <small>{comanda.motivo_revisao}</small>}</td></tr>)}{!loading && !comandas.length && <tr><td colSpan={5}>Nenhuma comanda enviada.</td></tr>}{loading && <tr><td colSpan={5}>Carregando…</td></tr>}</tbody></table></div><section className="admin-operator-invite"><h2>Próxima barreira de segurança</h2><p>Antes de criar QR, esta comanda precisa ser vinculada a uma venda paga que a Saipos retorne. Enquanto a Mesa 99 não aparecer na API, nenhuma confirmação positiva será oferecida aqui.</p></section></div>;
}
