'use client';

import { useEffect, useState } from 'react';
import { fetchAdmin } from '@/lib/adminFetch';
import { useAdminCanChange } from '../adminAccessContext';

type Comanda = { id: string; status: string; mesa_referencia: string; id_pedido_impresso?: string | null; valor_confirmado?: number | null; saipos_sale_id?: string | null; reconciliacao_status?: string | null; reconciliacao_detalhes?: { motivo?: string } | null; criado_por_nome?: string | null; criado_em: string; revisada_por_nome?: string | null; revisada_em?: string | null; motivo_revisao?: string | null; expira_em: string };

export default function ComandasPage() {
  const canChange = useAdminCanChange();
  const [comandas, setComandas] = useState<Comanda[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [images, setImages] = useState<Array<{ tipo: string; url: string }> | null>(null); const [working, setWorking] = useState<string | null>(null);
  async function carregar() { setLoading(true); try { const response = await fetchAdmin('/api/roleta-v2/comandas', { cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Não foi possível carregar.'); setComandas(data.comandas || []); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível carregar.'); } finally { setLoading(false); } }
  useEffect(() => { carregar(); }, []);
  async function abrirFoto(id: string) { setError(''); try { const response = await fetchAdmin(`/api/roleta-v2/comandas/${id}/imagem`, { cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Não foi possível abrir as fotos.'); setImages(data.imagens); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível abrir as fotos.'); } }
  async function revisar(id: string, acao: 'em_analise' | 'rejeitada') { const motivo = window.prompt(acao === 'rejeitada' ? 'Motivo da rejeição:' : 'Registro da conferência:'); if (!motivo || motivo.trim().length < 3) return; setWorking(id); try { const response = await fetchAdmin(`/api/roleta-v2/comandas/${id}/revisar`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ acao, motivo }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Não foi possível registrar a revisão.'); await carregar(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível registrar a revisão.'); } finally { setWorking(null); } }
  return <div className="admin-operators"><section className="admin-notice"><strong>Piloto com duas evidências</strong><span>Garçom envia duas fotos e confirma mesa, horário, ID e valor. O QR é único; a Saipos confere depois, sem consequência automática.</span></section>{!canChange && <div className="admin-notice"><span>Gestão consulta fotos e resultados; só o superadmin pode alterar a revisão.</span></div>}{error && <div className="admin-notice error"><span>{error}</span></div>}{images && <section className="admin-operator-invite"><div className="admin-section-title"><div><span>Fotos privadas</span><h2>Conferir comanda</h2></div><button onClick={() => setImages(null)}>Fechar</button></div><div className="grid gap-4 md:grid-cols-2">{images.map((imagem) => <figure key={imagem.tipo}><figcaption className="mb-2 font-bold">{imagem.tipo === 'cabecalho' ? 'Parte de cima: mesa e horário' : 'Parte de baixo: total/fechamento'}</figcaption><img src={imagem.url} alt={`Foto privada da comanda: ${imagem.tipo}`} className="max-h-[70vh] rounded-lg border border-stone-300" /></figure>)}</div></section>}<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Quando</th><th>Mesa / pedido</th><th>Enviado por</th><th>QR</th><th>Saipos</th><th>Conferência</th></tr></thead><tbody>{comandas.map((comanda) => <tr key={comanda.id}><td>{new Date(comanda.criado_em).toLocaleString('pt-BR')}</td><td><strong>{comanda.mesa_referencia}</strong><br /><small>{comanda.id_pedido_impresso ? `Pedido ${comanda.id_pedido_impresso}` : 'Aguardando confirmação'}</small></td><td>{comanda.criado_por_nome || '—'}</td><td>{comanda.status}</td><td><strong>{comanda.reconciliacao_status || 'pendente'}</strong>{comanda.reconciliacao_detalhes?.motivo && <small>{comanda.reconciliacao_detalhes.motivo}</small>}</td><td><button onClick={() => abrirFoto(comanda.id)}>Ver 2 fotos</button>{canChange && ['aguardando_confirmacao', 'em_analise'].includes(comanda.status) && <><button onClick={() => revisar(comanda.id, 'em_analise')} disabled={working === comanda.id}>{working === comanda.id ? 'Salvando…' : 'Em análise'}</button><button className="admin-danger-button" onClick={() => revisar(comanda.id, 'rejeitada')} disabled={working === comanda.id}>Rejeitar</button></>} {comanda.motivo_revisao && <small>{comanda.motivo_revisao}</small>}</td></tr>)}{!loading && !comandas.length && <tr><td colSpan={6}>Nenhuma comanda enviada.</td></tr>}{loading && <tr><td colSpan={6}>Carregando…</td></tr>}</tbody></table></div><section className="admin-operator-invite"><h2>Reconciliação posterior</h2><p>Às 07:00 BRT (janela de execução da Vercel), o cron consulta somente comandas pendentes pelos IDs impressos. Compatível, divergente ou não localizada ficam registrados aqui e na auditoria; não há punição nem ajuste automático.</p></section></div>;
}
