import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';

// Read-only catalog inspection of production on 01/10/2026 identified these
// outstanding defects. These are local characterizations, NOT production writes
// or acceptance tests declaring signup/redemption ready. No customer rows copied.
test('schema real: usar_resgate_legado ainda referencia concluido_em ausente', async () => {
  const db = new PGlite();
  try {
    await db.exec(`create table public.resgates (
      id bigint primary key, telefone text not null, tipo text not null, valor numeric,
      codigo text not null, criado_em timestamptz not null default now(), usado_em timestamptz,
      produto_id integer, premio_nome text, status text default 'pendente', codigo_hash text);
      create table public.administracao_eventos (
        entidade text, entidade_id text, acao text, actor_user_id uuid, actor_email text, detalhes jsonb);
      insert into public.resgates(id,telefone,tipo,codigo) values (1,'fixture','produto','FIXTURE');`);
    const migration = await readFile(new URL('../supabase/migrations/202609160001_hardening_critico_legado.sql', import.meta.url), 'utf8');
    const definition = migration.match(/create or replace function public\.usar_resgate_legado\([\s\S]*?\$\$;/)?.[0];
    assert.ok(definition);
    await db.exec(definition);
    await assert.rejects(db.query("select public.usar_resgate_legado('FIXTURE',null,null,'fixture')"),
      (error: unknown) => {
        const e = error as { code: string; message: string };
        return e.code === '42703' && e.message.includes('concluido_em');
      });
    assert.equal((await db.query<{ usado_em: null }>('select usado_em from public.resgates where id=1')).rows[0].usado_em, null);
  } finally { await db.close(); }
});

test('schema real: unique_nome impede clientes homônimos mesmo com telefones diferentes', async () => {
  const db = new PGlite();
  try {
    await db.exec(`create table public.base_clientes_saipos (
      id bigint generated by default as identity primary key, nome text not null,
      telefone text, constraint unique_nome unique(nome), constraint unique_telefone unique(telefone));
      insert into public.base_clientes_saipos(nome,telefone) values ('Pessoa de fixture','fixture-a');`);
    await assert.rejects(db.query("insert into public.base_clientes_saipos(nome,telefone) values ('Pessoa de fixture','fixture-b')"),
      (error: unknown) => {
        const e = error as { code: string; message: string };
        return e.code === '23505' && e.message.includes('unique_nome');
      });
    assert.equal((await db.query<{ total: number }>('select count(*)::int as total from public.base_clientes_saipos')).rows[0].total, 1);
  } finally { await db.close(); }
});
