-- Disposable subset of the columns used in the real signup flow.
-- Not schema_base: includes the legacy name constraint that broke production.
create role anon;
create role authenticated;
create role service_role;
create table public.base_clientes_saipos (
  id bigint generated by default as identity primary key,
  nome text not null, telefone text not null, email text unique, cpf text unique,
  pin_hash text, data_nascimento date, nivel text default 'BRONZE', pontos integer default 0,
  cashback numeric default 0, tickets integer default 0, total_gasto numeric default 0,
  qtd_pedidos integer default 0, primeira_compra timestamptz, ultima_compra timestamptz,
  atualizado_em timestamptz default now(),
  constraint unique_nome unique(nome), constraint unique_telefone unique(telefone)
);
create table public.extrato_pontos (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.base_clientes_saipos(id),
  tipo text not null check(tipo in ('entrada','saida')), valor numeric not null,
  origem text, descricao text, criado_em timestamptz default now(), metodo text
);
create table public.seguranca_configuracoes(id smallint primary key,modo_contencao boolean not null);
insert into public.seguranca_configuracoes values(1,false);
