begin;

-- Colunas aditivas: a migração não apaga nem recalcula saldos existentes.
alter table if exists public.base_clientes_saipos
  add column if not exists auth_user_id uuid references auth.users(id) on delete set null,
  add column if not exists gasto_90_dias numeric(12,2) check (gasto_90_dias >= 0),
  add column if not exists fracao_ticket numeric(12,4) not null default 0 check (fracao_ticket >= 0),
  add column if not exists marketing_opt_in boolean not null default false,
  add column if not exists marketing_opt_in_em timestamptz,
  add column if not exists marketing_opt_out_em timestamptz,
  add column if not exists nivel_calculado_em timestamptz;

create unique index if not exists base_clientes_auth_user_unique
  on public.base_clientes_saipos(auth_user_id)
  where auth_user_id is not null;

create index if not exists base_clientes_telefone_idx
  on public.base_clientes_saipos(telefone);

create index if not exists base_clientes_ultima_compra_idx
  on public.base_clientes_saipos(ultima_compra desc);

create table if not exists public.fidelidade_transacoes (
  id bigint generated by default as identity primary key,
  id_sale text not null unique,
  cliente_id bigint not null,
  valor_elegivel numeric(12,2) not null check (valor_elegivel > 0),
  nivel_antes text not null check (nivel_antes in ('bronze','prata','ouro','rei')),
  nivel_depois text not null check (nivel_depois in ('bronze','prata','ouro','rei')),
  pontos_gerados integer not null default 0 check (pontos_gerados >= 0),
  cashback_gerado numeric(12,2) not null default 0 check (cashback_gerado >= 0),
  tickets_gerados integer not null default 0 check (tickets_gerados >= 0),
  ocorreu_em timestamptz not null,
  criado_em timestamptz not null default now()
);

create index if not exists fidelidade_transacoes_cliente_data_idx
  on public.fidelidade_transacoes(cliente_id, ocorreu_em desc);

create table if not exists public.auditoria_fidelidade (
  id bigint generated by default as identity primary key,
  ator_id uuid,
  cliente_id bigint,
  acao text not null,
  entidade text not null,
  entidade_id text,
  detalhes jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now()
);

create index if not exists auditoria_fidelidade_cliente_data_idx
  on public.auditoria_fidelidade(cliente_id, criado_em desc);

alter table public.fidelidade_transacoes enable row level security;
alter table public.auditoria_fidelidade enable row level security;

-- Sem policies públicas: somente o backend com service role acessa estes ledgers.
revoke all on public.fidelidade_transacoes from anon, authenticated;
revoke all on public.auditoria_fidelidade from anon, authenticated;

comment on column public.base_clientes_saipos.gasto_90_dias is
  'Cache do gasto elegível nos 90 dias anteriores. NULL significa aguardando backfill seguro da Saipos.';
comment on column public.base_clientes_saipos.fracao_ticket is
  'Saldo fracionário transportado entre compras para ninguém perder tickets por arredondamento.';

create or replace function public.creditar_venda_fidelidade(
  p_cliente_id bigint,
  p_id_sale bigint,
  p_valor numeric,
  p_ocorreu_em timestamptz default now()
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_cliente public.base_clientes_saipos%rowtype;
  v_gasto_anterior numeric;
  v_gasto_depois numeric;
  v_nivel_antes text;
  v_nivel_depois text;
  v_pontos_mult integer;
  v_cashback_taxa numeric;
  v_tickets_mult integer;
  v_pontos integer;
  v_cashback numeric;
  v_tickets_bruto numeric;
  v_tickets integer;
begin
  if p_valor <= 0 then raise exception 'Valor elegível deve ser positivo'; end if;

  insert into public.saipos_pedidos_processados(id_sale)
  values (p_id_sale)
  on conflict (id_sale) do nothing;
  if not found then return jsonb_build_object('duplicada', true); end if;

  select * into v_cliente
  from public.base_clientes_saipos
  where id = p_cliente_id
  for update;
  if not found then raise exception 'Cliente não encontrado'; end if;

  v_gasto_anterior := coalesce(v_cliente.gasto_90_dias, v_cliente.total_gasto, 0);
  v_gasto_depois := v_gasto_anterior + p_valor;

  if v_gasto_anterior >= 500 then
    v_nivel_antes := 'rei'; v_pontos_mult := 7; v_cashback_taxa := .03; v_tickets_mult := 10;
  elsif v_gasto_anterior >= 250 then
    v_nivel_antes := 'ouro'; v_pontos_mult := 4; v_cashback_taxa := .01; v_tickets_mult := 5;
  elsif v_gasto_anterior >= 100 then
    v_nivel_antes := 'prata'; v_pontos_mult := 2; v_cashback_taxa := .005; v_tickets_mult := 2;
  else
    v_nivel_antes := 'bronze'; v_pontos_mult := 1; v_cashback_taxa := 0; v_tickets_mult := 1;
  end if;

  v_nivel_depois := case
    when v_gasto_depois >= 500 then 'rei'
    when v_gasto_depois >= 250 then 'ouro'
    when v_gasto_depois >= 100 then 'prata'
    else 'bronze' end;
  v_pontos := floor(p_valor * v_pontos_mult);
  v_cashback := round(p_valor * v_cashback_taxa, 2);
  v_tickets_bruto := coalesce(v_cliente.fracao_ticket, 0) + (p_valor / 100 * v_tickets_mult);
  v_tickets := floor(v_tickets_bruto);

  update public.base_clientes_saipos set
    nivel = v_nivel_depois,
    pontos = coalesce(pontos, 0) + v_pontos,
    cashback = coalesce(cashback, 0) + v_cashback,
    tickets = coalesce(tickets, 0) + v_tickets,
    fracao_ticket = v_tickets_bruto - v_tickets,
    total_gasto = coalesce(total_gasto, 0) + p_valor,
    gasto_90_dias = v_gasto_depois,
    qtd_pedidos = coalesce(qtd_pedidos, 0) + 1,
    ultima_compra = p_ocorreu_em,
    atualizado_em = now(),
    nivel_calculado_em = now()
  where id = p_cliente_id;

  insert into public.fidelidade_transacoes(
    id_sale, cliente_id, valor_elegivel, nivel_antes, nivel_depois,
    pontos_gerados, cashback_gerado, tickets_gerados, ocorreu_em
  ) values (
    p_id_sale::text, p_cliente_id, p_valor, v_nivel_antes, v_nivel_depois,
    v_pontos, v_cashback, v_tickets, p_ocorreu_em
  );

  return jsonb_build_object(
    'duplicada', false, 'nivel_antes', v_nivel_antes, 'nivel_depois', v_nivel_depois,
    'pontos', v_pontos, 'cashback', v_cashback, 'tickets', v_tickets,
    'gasto_90_dias', v_gasto_depois
  );
end;
$$;

revoke all on function public.creditar_venda_fidelidade(bigint,bigint,numeric,timestamptz) from public, anon, authenticated;
grant execute on function public.creditar_venda_fidelidade(bigint,bigint,numeric,timestamptz) to service_role;

commit;
